public with sharing class test {
    // public test() {
    //     List<SQX_Exam__c> examRecords = [
    //         SELECT Id, SQX_Set__c
    //         FROM SQX_Exam__c
    //         WHERE SQX_Assign_To__r.Username = :UserInfo.getUserId()
    //     ];

    //     Set<Id> questionSetIds = new Set<Id>();
    //     for (SQX_Exam__c exam : examRecords) {
    //         questionSetIds.add(exam.SQX_Set__c);
    //     }

    // }
}